version: '3.8'

services:
  nestapp:
    container_name: nestapp
    image: oussamabouchikhi/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env.production
    environment:
      DB_TYPE: $DB_TYPE
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
      DB_SYNC: $DB_SYNC
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5433:5432
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
